name = "diabetescalculator"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-12-12"
assets.directory = ".svelte-kit/cloudflare"
assets.binding = "ASSETS" # Exclude this if you don't have a `main` key configured.